### ISSUE TITLE
How to get root access on dotOS 2.1?

### ISSUE THREAD

**Issue by DesertsP** [DotOS/android_vendor_dot#53]
How can I root dot 2.1? I have tried Magisk, supersu, and lineage addonsu and all failed.

**Comment by Cladt** [comment]
what do you mean by failed? i've seen that if you try to root an oreo (8.1) rom after you flash supersu or magisk you need to install manually the supersu app (or magisk app) from the zip file that you've flashed before, then you'll be able to use root

**Comment by BitchDealer998** [comment]
> what do you mean by failed? i've seen that if you try to root an oreo (8.1) rom after you flash supersu or magisk you need to install manually the supersu app (or magisk app) from the zip file that you've flashed before, then you'll be able to use root

i've tried it and it still bootlop just as same as when i tried super su, any advice?
