### ISSUE TITLE
Unable to install supersu or magisk with version 2.5 OTA

### ISSUE THREAD

**Issue by aajiwani** [DotOS/android_vendor_dot#63]
After I installed the OTA, the root access was gone from my phone. But later when I tried to flash supersu.zip or magisk.zip I cannot get it to work.

---

**In case of Magisk**:
- It says that cannot unmount /vendor, I believe its failing there
- ![Magisk Screenshot](https://user-images.githubusercontent.com/844545/46122132-a1ef0f00-c249-11e8-9f09-0f5abbe95d10.jpg)

---

**In case of SuperSU**:
- It fails on Boot image patcher process, right after patching sepolicy. It says failure, aborting.
- ![SuperSU Screenshot](https://user-images.githubusercontent.com/844545/46122119-94398980-c249-11e8-970d-9e7ecd8cfd70.jpg)

**Comment by Sweeto143** [comment]
@aajiwani Wew

**Comment by mohancm** [comment]
@aajiwani which device?
